language: generic
dist: trusty
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -y update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confnew" --force-yes install docker-engine
script:
  - make test
after_success:
  - make push
